apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: go-dep
  template:
    metadata:
      labels:
        name: go-dep
    spec:
      containers:
        - name: golang-pod
          image: dinesh790/golang-dockercompose # image pulled from dockerhub
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: golang-service
spec:
  type: NodePort
  selector:
      name: go-dep
  ports:    
    - port: 8080
      targetPort: 8080
      nodePort: 30080
