server:
  service:
    type: NodePort
    nodePort: 32000
  extraScrapeConfigsSecret: prometheus-additional-scrape-configs  
  # additionalScrapeConfigs:
  #   - job_name: "golang-app"
  #     static_configs:
  #       - target: ["golang-service:8080"]